name = "sefinek-blocklist-edge-cache"
main = "worker.js"
compatibility_date = "2026-01-01"

routes = [
  { pattern = "blocklist.sefinek.net/generated/v1/0.0.0.0/porn/chadmayfield/pi-blocklist-porn-all.fork.txt", zone_name = "sefinek.net" },
  { pattern = "blocklist.sefinek.net/generated/v1/0.0.0.0/porn/blocklistproject/porn.fork.txt", zone_name = "sefinek.net" },
  { pattern = "blocklist.sefinek.net/generated/v1/0.0.0.0/ransomware/blocklistproject/ransomware.fork.txt", zone_name = "sefinek.net" },
  { pattern = "blocklist.sefinek.net/generated/v1/0.0.0.0/ads/adaway/hosts.fork.txt", zone_name = "sefinek.net" },
  { pattern = "blocklist.sefinek.net/generated/v1/0.0.0.0/ads/disconnectme/simple-ad.fork.txt", zone_name = "sefinek.net" },
  { pattern = "blocklist.sefinek.net/generated/v1/0.0.0.0/malicious/DandelionSprout-AntiMalwareHosts.fork.txt", zone_name = "sefinek.net" },
  { pattern = "blocklist.sefinek.net/generated/v1/0.0.0.0/ads/firebog/AdguardDNS.fork.txt", zone_name = "sefinek.net" },
  { pattern = "blocklist.sefinek.net/generated/v1/0.0.0.0/phishing/blocklistproject/phishing.fork.txt", zone_name = "sefinek.net" },
  { pattern = "blocklist.sefinek.net/generated/v1/0.0.0.0/ads/craiu/mobiletrackers.fork.txt", zone_name = "sefinek.net" },
  { pattern = "blocklist.sefinek.net/generated/v1/0.0.0.0/malicious/AssoEchap/stalkerware-indicators.fork.txt", zone_name = "sefinek.net" },
  { pattern = "blocklist.sefinek.net/generated/v1/0.0.0.0/ads/blocklistproject/hosts.fork.txt", zone_name = "sefinek.net" },
  { pattern = "blocklist.sefinek.net/generated/v1/0.0.0.0/ads/firebog/Prigent-Ads.fork.txt", zone_name = "sefinek.net" },
  { pattern = "blocklist.sefinek.net/generated/v1/0.0.0.0/ads/crazy-max/spy.fork.txt", zone_name = "sefinek.net" },
  { pattern = "blocklist.sefinek.net/generated/v1/0.0.0.0/tracking-and-telemetry/0Zinc/easyprivacy.fork.txt", zone_name = "sefinek.net" },
  { pattern = "blocklist.sefinek.net/generated/v1/0.0.0.0/malicious/malware-filter/urlhaus-filter-hosts-online.fork.txt", zone_name = "sefinek.net" },
  { pattern = "blocklist.sefinek.net/generated/v1/0.0.0.0/ads/firebog/Admiral.fork.txt", zone_name = "sefinek.net" },
  { pattern = "blocklist.sefinek.net/generated/v1/0.0.0.0/phishing/Dogino/Discord-Phishing-URLs-phishing.fork.txt", zone_name = "sefinek.net" },
  { pattern = "blocklist.sefinek.net/generated/v1/0.0.0.0/phishing/RPiList/Phishing-Angriffe.fork.txt", zone_name = "sefinek.net" },
  { pattern = "blocklist.sefinek.net/generated/v1/0.0.0.0/malicious/quidsup/notrack-malware.fork.txt", zone_name = "sefinek.net" },
  { pattern = "blocklist.sefinek.net/generated/v1/0.0.0.0/ads/yoyo/ads-trackers-etc.fork.txt", zone_name = "sefinek.net" },
  { pattern = "blocklist.sefinek.net/generated/v1/0.0.0.0/ads/firebog/Easylist.fork.txt", zone_name = "sefinek.net" },
  { pattern = "blocklist.sefinek.net/generated/v1/0.0.0.0/malicious/disconnectme/simple-malvertising.fork.txt", zone_name = "sefinek.net" },
  { pattern = "blocklist.sefinek.net/generated/v1/0.0.0.0/tracking-and-telemetry/neodevpro/host.fork.txt", zone_name = "sefinek.net" },
  { pattern = "blocklist.sefinek.net/generated/v1/0.0.0.0/tracking-and-telemetry/MajkiIT/adguard-mobile-host.fork.txt", zone_name = "sefinek.net" },
  { pattern = "blocklist.sefinek.net/generated/v1/0.0.0.0/phishing/phishing.army/blocklist-extended.fork.txt", zone_name = "sefinek.net" },
  { pattern = "blocklist.sefinek.net/generated/v1/0.0.0.0/tracking-and-telemetry/frogeye/firstparty-trackers-hosts.txt", zone_name = "sefinek.net" },
  { pattern = "blocklist.sefinek.net/generated/v1/0.0.0.0/malicious/blocklistproject/malware.fork.txt", zone_name = "sefinek.net" },
  { pattern = "blocklist.sefinek.net/generated/v1/0.0.0.0/ads/DandelionSprout.GameConsoleAdblockList.txt", zone_name = "sefinek.net" },
  { pattern = "blocklist.sefinek.net/generated/v1/0.0.0.0/malicious/bigdargon/hostsVN.fork.txt", zone_name = "sefinek.net" },
  { pattern = "blocklist.sefinek.net/generated/v1/0.0.0.0/ads/MajkiIT/SmartTV-ads.fork.txt", zone_name = "sefinek.net" },
  { pattern = "blocklist.sefinek.net/generated/v1/0.0.0.0/malicious/Spam404/main-blacklist.fork.txt", zone_name = "sefinek.net" },
  { pattern = "blocklist.sefinek.net/generated/v1/0.0.0.0/ads/r-a-y/AdguardMobileAds.fork.txt", zone_name = "sefinek.net" },
  { pattern = "blocklist.sefinek.net/generated/v1/0.0.0.0/malicious/phishing.txt", zone_name = "sefinek.net" },
  { pattern = "blocklist.sefinek.net/generated/v1/0.0.0.0/malicious/RPiList/Malware.fork.txt", zone_name = "sefinek.net" },
  { pattern = "blocklist.sefinek.net/generated/v1/0.0.0.0/ads/ShadowWhisperer/Ads.fork.txt", zone_name = "sefinek.net" },
  { pattern = "blocklist.sefinek.net/generated/v1/0.0.0.0/malicious/reported-by-norton.txt", zone_name = "sefinek.net" },
  { pattern = "blocklist.sefinek.net/generated/v1/0.0.0.0/malicious/web-attacks.txt", zone_name = "sefinek.net" },
  { pattern = "blocklist.sefinek.net/generated/v1/0.0.0.0/ads/sefinek.hosts.txt", zone_name = "sefinek.net" },
  { pattern = "blocklist.sefinek.net/generated/v1/0.0.0.0/porn/oisd/nsfw.fork.txt", zone_name = "sefinek.net" },
  { pattern = "blocklist.sefinek.net/generated/v1/0.0.0.0/gambling/sefinek.hosts2.txt", zone_name = "sefinek.net" },
]
